name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs Every Day

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: 'ttdehof' # Hashnode Username
          BLOG_URL: 'https://blog.timdehof.dev/' # Blog URL
          COUNT: 6 # MAX Visisble
          STYLE: "blog-alternate"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
